### ISSUE TITLE
Passing objects by referrence instead by value.

### ISSUE THREAD

**Issue by silviucpp** [jtilly/inih#16]
Hello,

I see all over the places that objects are passed by value instead by reference:

```c++
INIReader(std::string filename);
```

You probably know that it is a bad idea to pass objects by value due to its performance impact.

Correct is:

```c++
INIReader(const std::string& filename);
```

**Comment by jtilly** [comment]
Fair point. This has been fixed upstream a while ago. It's probably time to pull these changes in here, too.
