### ISSUE TITLE
Warning when compiling with gcc 9

### ISSUE THREAD

**Issue by Crayon2000** [jtilly/inih#17]
Issue is in our code, sorry!

**Comment by Crayon2000** [comment]
Issue is in our code, sorry!

**Comment by Crayon2000** [comment]
After some investigation, it seems there is a warning with the latest gcc version.

The fist time I encountered the problem was when using this version of gcc for ARM:
```
arm-linux-gnueabihf-g++ (GNU Toolchain for the A-profile Architecture 8.3-2019.03 (arm-rel-8.36)) 8.3.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
I was using the `-Werror` switch so I thought it was an error.

So I tried to reproduce the same problem with gcc for Ubuntu:
```
g++-8 (Ubuntu 8.3.0-6ubuntu1~18.04.1) 8.3.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
I was not able to reproduce, so that's why I concluded it was error in our code.

I did some testing in PR #18 and I was finally able to reproduce the problem with gcc 9.
All warnings and optimization needs to be turn on: `-O2 -Wall`

This is the warning I am getting when compiling the INIReaderTest application:
```
In file included from /usr/include/string.h:635,
                 from INIReader.h:114,
                 from INIReaderTest.cpp:5:
In function ‘char* strncpy(char*, const char*, size_t)’,
    inlined from ‘int ini_parse_stream(ini_reader, void*, ini_handler, void*)’ at INIReader.h:163:12,
    inlined from ‘int ini_parse(const char*, ini_handler, void*)’ at INIReader.h:283:28,
    inlined from ‘INIReader::INIReader(std::string)’ at INIReader.h:377:23,
    inlined from ‘int main()’ at INIReaderTest.cpp:18:32:
/usr/include/x86_64-linux-gnu/bits/string3.h:126:34: warning: ‘char* __builtin_strncpy(char*, const char*, long unsigned int)’ specified bound 50 equals destination size [-Wstringop-truncation]
  126 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
      |          ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In function ‘char* strncpy(char*, const char*, size_t)’,
    inlined from ‘int ini_parse_stream(ini_reader, void*, ini_handler, void*)’ at INIReader.h:163:12,
    inlined from ‘int ini_parse(const char*, ini_handler, void*)’ at INIReader.h:283:28,
    inlined from ‘INIReader::INIReader(std::string)’ at INIReader.h:377:23,
    inlined from ‘int main()’ at INIReaderTest.cpp:18:32:
/usr/include/x86_64-linux-gnu/bits/string3.h:126:34: warning: ‘char* __builtin_strncpy(char*, const char*, long unsigned int)’ output may be truncated copying 50 bytes from a string of length 199 [-Wstringop-truncation]
  126 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
      |          ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
You can confirm by looking at the PR result for g++ 9 at https://travis-ci.org/jtilly/inih/pull_requests

I found a really interesting article on this new warning: https://developers.redhat.com/blog/2018/05/24/detecting-string-truncation-with-gcc-8/

If you read the *Mitigating strncpy Truncation* section, it seems you are doing the good thing in your code.

For some reason it will work if you replace the inline `strncpy0` function with this MACRO:
```cpp
#define strncpy0(dest, src, size) \
    do { \
        strncpy(dest, src, size); \
        dest[size - 1] = '\0'; \
    } while (false)
```
Using a MACRO was inspired by this PR: `https://github.com/intel/openlldp/pull/27`

PR #18 is ready to be merged if you want to test with multiple compilers. I don't mind if you close it, if you consider it is not necessary.

For this issue, if you consider that changes are required to the code to fix the warning, you could reopen it, if not, keep it closed.

Sorry for this long message.

**Comment by jtilly** [comment]
Thanks for investigating and sharing! I'll take a look.

**Comment by lss4** [comment]
Can confirm the warnings when compiling using both `-O2` and `-Wall` with g++ 9.3.0. The warnings do not appear with `-Wall` alone, or using `-O1`.

The optimization process may have generated this `-Wall` visible warning. The warnings went away after replacing `strncpy0` with Crayon2000's macro as suggested above.
