### ISSUE TITLE
Quoting values containing '/' leads to misinterpretation, missing quotation support

### ISSUE THREAD

**Issue by choopm** [jtilly/inih#4]
Take this .ini file as reference:
```
[database-mysql]
hostA = "tcp://127.0.0.1:3306"
hostB = tcp://127.0.0.1:3306
```
When trying to retrieve hostA, it will evaluate to `"tcp` while hostB evaluates correctly.
As shown in [INI file](https://en.wikipedia.org/wiki/INI_file#Example), quoting of values should be perfectly fine. The closing `"` is missing too.

By looking at the code, it seems to me that quoting wasn't considered at all. Is this on purpose?

**Comment by jtilly** [comment]
This repo is just a fork of https://github.com/benhoyt/inih. If it's not implemeted there, then it is also not included here.  I'm currently not working on this, but you're welcome to send a pull request.

**Comment by choopm** [comment]
The original maintainer isn't working on the C++ API anymore. As this feature isn't documented, I was just falsely assuming it might have been implemented.
Closing this issue, thanks for the fast response 😄
